# fly.toml app configuration file generated for rtcchat on 2023-10-05T12:40:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rtcchat"
primary_region = "arn"

[build]

[env]
  PORT = "4000"
  NODE_ENV = "production"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
